### ISSUE TITLE
Issue conflicting with mondosk.

### ISSUE THREAD

**Issue by korbynullevig** [TlatoaniHJ/ThatPacketAddon#4]
So i just installed this and im using the set display skin from mondosk and when i have this installed it breaks and makes it so i cant use the set display skin. Could you move the set display skin from mondosk to ThatPacketAddon?

**Comment by TlatoaniHJ** [comment]
Setting displayed skin is available in Tablisknu. You should use Tablisknu instead of MundoSK if you want to use ThatPacketAddon.

**Comment by korbynullevig** [comment]
thanks for the responce. I installed that and now it works but when i switch to a new skin it gives me this error 

`08:54 INFO]: [Tablisknu] An exception has occured within Tablisknu
[20:08:54 INFO]: [Tablisknu] Please create an issue regarding this on Tablisknu's GitHub page: (no github link available yet, but you can join the skript discord chat at https://discord.gg/vb9dGbu for help)
[20:08:54 INFO]: [Tablisknu] You can also run the '/tablisknu desc' command and go to one of the links provided for help.
[20:08:54 INFO]: [Tablisknu] Bukkit/Spigot version: git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)
[20:08:54 INFO]: [Tablisknu] Skript version: 2.2-dev36
[20:08:54 INFO]: [Tablisknu] Tablisknu version: 1.0
[20:08:54 INFO]: [Tablisknu] Exception at ProfileManager
[20:08:54 WARN]: java.lang.NullPointerException
[20:08:54 WARN]:        at us.tlatoani.tablisknu.skin.ProfileManager.respawnPlayer(ProfileManager.java:255)
[20:08:54 WARN]:        at us.tlatoani.tablisknu.skin.ProfileManager.refreshPlayer(ProfileManager.java:231)
[20:08:54 WARN]:        at us.tlatoani.tablisknu.skin.ModifiableProfile$Specific.changeDisplayedSkin(ModifiableProfile.java:141)
[20:08:54 WARN]:        at us.tlatoani.tablisknu.skin.ModifiableProfile$Specific.access$300(ModifiableProfile.java:128)
[20:08:54 WARN]:        at us.tlatoani.tablisknu.skin.ModifiableProfile.lambda$consistentlySetDisplayedSkin$6(ModifiableProfile.java:104)
[20:08:54 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[20:08:54 WARN]:        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[20:08:54 WARN]:        at java.util.Iterator.forEachRemaining(Unknown Source)
[20:08:54 WARN]:        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
[20:08:54 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[20:08:54 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[20:08:54 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[20:08:54 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[20:08:54 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[20:08:54 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[20:08:54 WARN]:        at us.tlatoani.tablisknu.skin.ModifiableProfile.consistentlySetDisplayedSkin(ModifiableProfile.java:102)
[20:08:54 WARN]:        at us.tlatoani.tablisknu.skin.ExprDisplayedSkinOfPlayer.change(ExprDisplayedSkinOfPlayer.java:108)
[20:08:54 WARN]:        at ch.njol.skript.effects.EffChange.execute(EffChange.java:271)
[20:08:54 WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:52)
[20:08:54 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:08:54 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:08:54 WARN]:        at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[20:08:54 WARN]:        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:93)
[20:08:54 WARN]:        at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[20:08:54 WARN]:        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
[20:08:54 WARN]:        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53)
[20:08:54 WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:52)
[20:08:54 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:08:54 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:08:54 WARN]:        at com.github.tukenuke.tuske.util.EffectSection.runSection(EffectSection.java:135)
[20:08:54 WARN]:        at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.lambda$execute$1(EffFormatGUI.java:146)
[20:08:54 WARN]:        at com.github.tukenuke.tuske.manager.gui.GUI.run(GUI.java:31)
[20:08:54 WARN]:        at com.github.tukenuke.tuske.manager.gui.GUIManager$1.onClick(GUIManager.java:149)
[20:08:54 WARN]:        at com.github.tukenuke.tuske.listeners.GUIListener.onEvent(GUIListener.java:57)
[20:08:54 WARN]:        at com.github.tukenuke.tuske.manager.gui.v2.SkriptGUIEvent.check(SkriptGUIEvent.java:39)
[20:08:54 WARN]:        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:145)
[20:08:54 WARN]:        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
[20:08:54 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:08:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[20:08:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[20:08:54 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1891)
[20:08:54 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[20:08:54 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[20:08:54 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:08:54 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:08:54 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[20:08:54 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[20:08:54 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[20:08:54 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:08:54 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:08:54 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[20:08:54 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by korbynullevig** [comment]
Im running spigot 1.12.2 - Skript version 2.2-dev36

**Comment by korbynullevig** [comment]
Error on boot


> [19:21:56 INFO]: [Tablisknu] Exception at ProfileManager
[19:21:56 WARN]: java.lang.IllegalStateException: Unable to find method moveToWorld ([class net.minecraft.server.v1_12_R1.EntityPlayer, class net.minecraft.server.v1_12_R1.DimensionManager, boolean, class org.bukkit.Location, boolean]).
[19:21:56 WARN]:        at us.tlatoani.tablisknu.core.reflection.Reflection.getTypedMethod(Reflection.java:289)
[19:21:56 WARN]:        at us.tlatoani.tablisknu.core.reflection.Reflection.getMethod(Reflection.java:250)
[19:21:56 WARN]:        at us.tlatoani.tablisknu.core.reflection.Reflection.getTypedMethod(Reflection.java:287)
[19:21:56 WARN]:        at us.tlatoani.tablisknu.core.reflection.Reflection.getMethod(Reflection.java:250)
[19:21:56 WARN]:        at us.tlatoani.tablisknu.core.reflection.Reflection.getTypedMethod(Reflection.java:287)
[19:21:56 WARN]:        at us.tlatoani.tablisknu.core.reflection.Reflection.getMethod(Reflection.java:250)
[19:21:56 WARN]:        at us.tlatoani.tablisknu.skin.ProfileManager.loadReflectionStuff(ProfileManager.java:65)
[19:21:56 WARN]:        at us.tlatoani.tablisknu.skin.ProfileManager.load(ProfileManager.java:46)
[19:21:56 WARN]:        at us.tlatoani.tablisknu.Tablisknu.onEnable(Tablisknu.java:65)
[19:21:56 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:21:56 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[19:21:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[19:21:56 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[19:21:56 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[19:21:56 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[19:21:56 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[19:21:56 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[19:21:56 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[19:21:56 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[19:21:56 WARN]:        at java.lang.Thread.run(Unknown Source)
